services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pontodoc-postgres:5432/${POSTGRES_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DS_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DS_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    ports:
      - "8080:8080"

  database:
    image: postgres
    container_name: pontodoc-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "${LOCAL_PORT}:${DOCKER_PORT}"